name: Tourism Project Pipeline

on:
  push:
    branches:
      - main

jobs:

  data-prep:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: pip install -r tourism_project/requirements.txt

      - name: Run Data Prep
        run: python tourism_project/model_building/prep.py

      - name: Upload processed data
        uses: actions/upload-artifact@v3
        with:
          name: processed-data
          path: tourism_project/data/

  model-training:
    needs: data-prep
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: pip install -r tourism_project/requirements.txt

      - name: Download processed data
        uses: actions/download-artifact@v3
        with:
          name: processed-data
          path: tourism_project/data/

      - name: Train Model
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python tourism_project/model_building/train.py

  deploy-hosting:
    needs: model-training
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: pip install -r tourism_project/requirements.txt

      - name: Deploy to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python tourism_project/hosting/hosting.py
