name: Tourism Project Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  register-dataset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          pip install pandas datasets huggingface_hub

      - name: Upload Dataset
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python mlops/model_building/prep.py


  data-prep:
    needs: register-dataset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          pip install pandas scikit-learn huggingface_hub

      - name: Run Data Prep
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python mlops/model_building/prep.py


  model-training:
    needs: data-prep
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          pip install pandas scikit-learn xgboost mlflow joblib huggingface_hub

      - name: Start MLflow
        run: |
          nohup mlflow ui --host 0.0.0.0 --port 5000 &
          sleep 10

      - name: Train Model
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python mlops/model_building/train.py


  deploy-hosting:
    needs: model-training
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          pip install huggingface_hub

      - name: Deploy to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python mlops/hosting/hosting.py
